// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(CustomerContext))]
    partial class CustomerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                       /* .IsRequired()*/
                        .HasColumnType("text");

                    b.Property<string>("GLAddition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GLCyilinder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GLIndex")
                        .HasColumnType("double precision");

                    b.Property<string>("GLPrizma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GLRAxis")
                        .HasColumnType("integer");

                    b.Property<string>("GLnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GPD")
                        .HasColumnType("integer");

                    b.Property<string>("GRAddition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GRAxis")
                        .HasColumnType("integer");

                    b.Property<string>("GRCyilinder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GRIndex")
                        .HasColumnType("double precision");

                    b.Property<string>("GRPrizma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GRnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LAxis")
                        .HasColumnType("integer");

                    b.Property<double>("LBC")
                        .HasColumnType("double precision");

                    b.Property<string>("LCyilinder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreGLAddition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreGLCyilinder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PreGLIndex")
                        .HasColumnType("double precision");

                    b.Property<string>("PreGLPrizma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PreGLRAxis")
                        .HasColumnType("integer");

                    b.Property<string>("PreGLnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PreGPD")
                        .HasColumnType("integer");

                    b.Property<string>("PreGRAddition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PreGRAxis")
                        .HasColumnType("integer");

                    b.Property<string>("PreGRCyilinder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PreGRIndex")
                        .HasColumnType("double precision");

                    b.Property<string>("PreGRPrizma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreGRnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RAxis")
                        .HasColumnType("integer");

                    b.Property<double>("RBC")
                        .HasColumnType("double precision");

                    b.Property<string>("RCyilinder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Custumers");
                });
#pragma warning restore 612, 618
        }
    }
}
